# Generated by Django 4.0.3 on 2022-03-14 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro1', '0003_alter_recipe_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='default_food.jpg', upload_to='food'),
        ),
    ]
