# Generated by Django 4.0.3 on 2022-03-18 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro1', '0009_alter_recipe_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, default='default_food.jpg', upload_to='food'),
        ),
    ]
